name: rksi_bloc
description: rksi schedule

version: 0.1.2+1

environment:
  sdk: ">=2.17.0-182.2.beta <3.0.0"

dependencies:
  flutter_bloc:
  bloc:
  equatable:
  connectivity_plus:
  http:
  google_fonts:
  provider:
  hive:
  hive_flutter:
  flutter:
    sdk: flutter
  cupertino_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  build_runner:
  hive_generator:

flutter:
  uses-material-design: true
